name: 'Get Latest Tag'
description: 'Retrieve the latest Git tag and increment the patch version'
inputs:
  default_version:
    description: 'Default version to use if no tags are found'
    required: false
    default: '0.0.0'
runs:
  using: 'composite'
  steps:
    - run: |
        # Captura a última tag ou define a versão padrão
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` || echo "${{ inputs.default_version }}")
        echo "Latest tag: $latest_tag"

        # Remove o prefixo 'v' caso exista e divide a versão
        IFS='.' read -ra VERSION <<< "${latest_tag#v}"
        major=${VERSION[0]:-0}
        minor=${VERSION[1]:-0}
        patch=${VERSION[2]:-0}

        # Incrementa o número de patch
        new_patch=$((patch + 1))
        new_version="$major.$minor.$new_patch"
        echo "New version: $new_version"

        # Define a nova versão como saída
        echo "version=$new_version" >> $GITHUB_ENV
      shell: bash